version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: employee_directory_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=employee_directory
    networks:
      - employee_network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: employee_directory_backend
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/employee_directory
      - DATA_SOURCE=excel
      - EXCEL_FILE_PATH=/app/data/EMPLOYEE_DIR.xlsx
      - HOST=0.0.0.0
      - PORT=8001
      - SECRET_KEY=employee-directory-secret-key
      - DEBUG=False
    volumes:
      - ./data:/app/data
      - ./backend/uploads:/app/uploads
    depends_on:
      - mongodb
    networks:
      - employee_network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: employee_directory_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8001
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - employee_network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: employee_directory_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    networks:
      - employee_network
    restart: unless-stopped

networks:
  employee_network:
    driver: bridge

volumes:
  mongodb_data: